export const sections = [
  {
    id: "immediate", emoji: "✨", label: "Right Away", sublabel: "First 1–2 weeks", color: "#c9a96e",
    items: [
      "Announce your engagement to close family & friends",
      "Post your engagement on social media (if desired)",
      "Take engagement photos (even casual phone photos to start)",
      "Set a rough budget for the wedding",
      "Decide on a general vision: intimate, large, destination, backyard, venue, etc.",
      "Discuss guest list size (rough number)",
      "Decide on a general timeframe (season / year)",
      "Start a shared folder (Google Drive, Notion, etc.) to organize everything",
      "Open a dedicated wedding bank account or savings fund",
    ],
  },
  {
    id: "early", emoji: "📅", label: "Early Planning", sublabel: "1–3 months out", color: "#a8c5a0",
    items: [
      "Create a full guest list with contact info",
      "Research and book your venue (venues book 12–18 months out)",
      "Set your wedding date",
      "Hire a wedding planner or day-of coordinator (if desired)",
      "Choose and ask your wedding party (bridesmaids, groomsmen, etc.)",
      "Start dress / suit shopping (dresses take 4–6 months to arrive)",
      "Book your photographer",
      "Book your videographer",
      "Research and book your officiant",
      "Start building your wedding website",
      "Begin honeymoon research and planning",
      "Create a wedding email address for vendor communication",
    ],
  },
  {
    id: "vendor", emoji: "🎶", label: "Vendors & Logistics", sublabel: "3–6 months out", color: "#9bb5d6",
    items: [
      "Book caterer / finalize food and beverage package with venue",
      "Book a band or DJ",
      "Book florist and discuss floral vision",
      "Book hair & makeup artist(s)",
      "Order wedding dress / suit / attire",
      "Order wedding party attire",
      "Book accommodations for out-of-town guests (hotel room block)",
      "Book transportation (shuttle, limo, vintage car, etc.)",
      "Design and send save-the-dates",
      "Research and book a rehearsal dinner venue",
      "Design and order wedding invitations",
      "Book a cake or dessert vendor",
      "Research wedding insurance",
      "Book honeymoon travel (flights, hotels, activities)",
      "Apply for passports if needed for honeymoon",
    ],
  },
  {
    id: "details", emoji: "💌", label: "The Details", sublabel: "4–6 months out", color: "#c9a0c5",
    items: [
      "Create your wedding registry",
      "Mail wedding invitations (6–8 weeks before wedding)",
      "Plan ceremony structure and write vows (if personal vows)",
      "Choose readings and music for ceremony",
      "Design ceremony programs",
      "Plan rehearsal dinner guest list and details",
      "Choose and order wedding favors",
      "Design seating chart (after RSVPs are in)",
      "Order name cards / place cards",
      "Plan day-of timeline with all vendors",
      "Design or order a wedding menu card",
      "Purchase wedding bands",
      "Schedule engagement photo session (if doing formal ones)",
      "Arrange for childcare at wedding if needed",
    ],
  },
  {
    id: "finalstretch", emoji: "🏁", label: "Final Stretch", sublabel: "1–2 months out", color: "#d6a88e",
    items: [
      "Track RSVPs and follow up with non-responders",
      "Finalize headcount and share with caterer",
      "Finalize seating chart",
      "Confirm all vendor bookings with final details",
      "Schedule final dress fitting",
      "Apply for marriage license (check local requirements for timing)",
      "Break in your wedding shoes",
      "Prepare vendor payment schedule and tip envelopes",
      "Delegate wedding-day tasks to trusted people",
      "Write a day-of emergency kit list (safety pins, stain remover, pain reliever, etc.)",
      "Prepare a 'wedding emergency kit' bag",
      "Create a vendor contact sheet for day-of coordinator or wedding party",
    ],
  },
  {
    id: "week", emoji: "🌹", label: "Wedding Week", sublabel: "7 days before", color: "#e8a0a0",
    items: [
      "Confirm all vendors one final time",
      "Deliver final payments and tip envelopes",
      "Hold wedding rehearsal",
      "Attend rehearsal dinner",
      "Prepare personal vows and speeches (print copies!)",
      "Pack honeymoon bags",
      "Delegate guest-wrangling duties to wedding party",
      "Get a good night's sleep the night before",
      "Eat a solid breakfast on wedding day",
      "Hand off rings to best man / maid of honor",
    ],
  },
  {
    id: "after", emoji: "🎊", label: "After the Wedding", sublabel: "Post-ceremony", color: "#a0c5c5",
    items: [
      "Send thank-you notes (aim for within 3 months)",
      "Return any rentals",
      "Preserve your wedding dress",
      "Change your name (if desired) — Social Security, license, passport, bank accounts",
      "Review and tip vendors (if not done already)",
      "Leave reviews for your vendors",
      "Share wedding photos with family",
      "Book anniversary dinner or trip",
      "Update beneficiaries on insurance and financial accounts",
      "Combine finances or update financial plans as a couple",
    ],
  },
];
